
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbfmdqwzvqxtyevuieta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiZm1kcXd6dnF4dHlldnVpZXRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NDIzNTgsImV4cCI6MjA1NzUxODM1OH0.EHrN7N8MCbTksogb4vllAt79NYnigKqLv1b9iA6qemE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
